/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FileType = IDL.Variant({
  'pdf' : IDL.Null,
  'audio' : IDL.Null,
  'other' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MedicalRecord = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileType' : FileType,
  'uploadDate' : IDL.Int,
  'blobReference' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PatientProfile = IDL.Record({
  'bloodType' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'profileId' : IDL.Text,
  'medications' : IDL.Vec(IDL.Text),
  'emergencyContactPhone' : IDL.Text,
  'conditions' : IDL.Vec(IDL.Text),
  'aiSummary' : IDL.Text,
  'emergencyContactName' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});
export const MedicalSummary = IDL.Record({
  'bloodType' : IDL.Text,
  'name' : IDL.Text,
  'emergencyContactPhone' : IDL.Text,
  'conditions' : IDL.Vec(IDL.Text),
  'emergencyContactName' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicalRecord' : IDL.Func([IDL.Text, MedicalRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'convertMedicalProfileToPatientProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [PatientProfile],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func([PatientProfile], [], []),
  'deleteMedicalRecord' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMedicalSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MedicalSummary)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(PatientProfile)], ['query']),
  'getPublicRecordsByProfileId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MedicalRecord)],
      ['query'],
    ),
  'getRecordsByProfileId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MedicalRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateAiSummary' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FileType = IDL.Variant({
    'pdf' : IDL.Null,
    'audio' : IDL.Null,
    'other' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MedicalRecord = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileType' : FileType,
    'uploadDate' : IDL.Int,
    'blobReference' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PatientProfile = IDL.Record({
    'bloodType' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'profileId' : IDL.Text,
    'medications' : IDL.Vec(IDL.Text),
    'emergencyContactPhone' : IDL.Text,
    'conditions' : IDL.Vec(IDL.Text),
    'aiSummary' : IDL.Text,
    'emergencyContactName' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const MedicalSummary = IDL.Record({
    'bloodType' : IDL.Text,
    'name' : IDL.Text,
    'emergencyContactPhone' : IDL.Text,
    'conditions' : IDL.Vec(IDL.Text),
    'emergencyContactName' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicalRecord' : IDL.Func([IDL.Text, MedicalRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'convertMedicalProfileToPatientProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [PatientProfile],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func([PatientProfile], [], []),
    'deleteMedicalRecord' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMedicalSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MedicalSummary)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(PatientProfile)], ['query']),
    'getPublicRecordsByProfileId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MedicalRecord)],
        ['query'],
      ),
    'getRecordsByProfileId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MedicalRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateAiSummary' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };